checkpoint: null
name: strong/svi
save_dir: ${env:EXPERIMENT_LOCATION}/Cam17_final
eval: true
checkpoint_metric: val_b_acc
data_class: Camelyon17BaseDataModule
data: ../default_Camelyon17BaseDataModule_strong.yaml
model_class: SVIResNetClassifier
model: ../../default_configs/default_SVIResNetClassifier.yaml
trainer: ../default_LightningTrainer_final.yaml