data_class: Camelyon17LabelNoiseDataModule
data:
  path: ${env:DATASET_LOCATION}/Camelyon17/tiles
  batch_size: 128
  num_workers: 8
  id_centers:
  - 0
  - 1
  - 3
  sampling_factor: -4.0
  val_subset: 1.0
  transformlib: torchvision
  augmentations: strong
  edge_label_flip: 0.25
  uniform_label_flip: 0.0
