callbacks:
  - class_path: pytorch_lightning.callbacks.TQDMProgressBar
    init_args:
      refresh_rate: 100
  - class_path: pytorch_lightning.callbacks.early_stopping.EarlyStopping
    init_args:
      monitor: val_loss
      patience: 5
      min_delta: 0.0
      verbose: false
      mode: min
      strict: true
      check_finite: true
      stopping_threshold: null
      divergence_threshold: null
      check_on_train_epoch_end: False
accelerator: gpu
devices: 1
strategy: null
precision: 16
num_sanity_val_steps: 0
reload_dataloaders_every_n_epochs: 1
move_metrics_to_cpu: false