data:
  path: ${env:DATASET_LOCATION}/Camelyon17/all
  batch_size: 128
  num_workers: 8
  tumor_threshold: 0.00
  id_centers:
  - 0
  - 1
  - 3
  transformlib: torchvision
  augmentations: crop
data_class: Camelyon17WholeSlideDataModule